array=(
../metrics
../metrics/16s
../metrics/16s/enet
../metrics/16s/enet/bool0
../metrics/16s/enet/abundance
../metrics/16s/lsvm
../metrics/16s/lsvm/bool0
../metrics/16s/lsvm/abundance
../metrics/16s/Random_forest
../metrics/16s/Random_forest/bool0
../metrics/16s/Random_forest/abundance
../metrics/16s/svm
../metrics/16s/svm/bool0
../metrics/16s/svm/abundance
../metrics/16s/lasso
../metrics/16s/lasso/bool0
../metrics/16s/lasso/abundance
../metrics/shotgun
../metrics/shotgun/enet
../metrics/shotgun/enet/bool0
../metrics/shotgun/enet/bool0/order
../metrics/shotgun/enet/bool0/family
../metrics/shotgun/enet/bool0/genus
../metrics/shotgun/enet/bool0/species
../metrics/shotgun/enet/abundance
../metrics/shotgun/enet/abundance/order
../metrics/shotgun/enet/abundance/family
../metrics/shotgun/enet/abundance/genus
../metrics/shotgun/enet/abundance/species
../metrics/shotgun/lsvm
../metrics/shotgun/lsvm/bool0
../metrics/shotgun/lsvm/bool0/order
../metrics/shotgun/lsvm/bool0/family
../metrics/shotgun/lsvm/bool0/genus
../metrics/shotgun/lsvm/bool0/species
../metrics/shotgun/lsvm/abundance
../metrics/shotgun/lsvm/abundance/order
../metrics/shotgun/lsvm/abundance/family
../metrics/shotgun/lsvm/abundance/genus
../metrics/shotgun/lsvm/abundance/species
../metrics/shotgun/Random_forest
../metrics/shotgun/Random_forest/bool0
../metrics/shotgun/Random_forest/bool0/order
../metrics/shotgun/Random_forest/bool0/family
../metrics/shotgun/Random_forest/bool0/genus
../metrics/shotgun/Random_forest/bool0/species
../metrics/shotgun/Random_forest/abundance
../metrics/shotgun/Random_forest/abundance/order
../metrics/shotgun/Random_forest/abundance/family
../metrics/shotgun/Random_forest/abundance/genus
../metrics/shotgun/Random_forest/abundance/species
../metrics/shotgun/Random_forest/bool001
../metrics/shotgun/Random_forest/bool001/order
../metrics/shotgun/Random_forest/bool001/family
../metrics/shotgun/Random_forest/bool001/genus
../metrics/shotgun/Random_forest/bool001/species
../metrics/shotgun/Random_forest/bool00001
../metrics/shotgun/Random_forest/bool00001/order
../metrics/shotgun/Random_forest/bool00001/family
../metrics/shotgun/Random_forest/bool00001/genus
../metrics/shotgun/Random_forest/bool00001/species
../metrics/shotgun/Random_forest/bool0001
../metrics/shotgun/Random_forest/bool0001/order
../metrics/shotgun/Random_forest/bool0001/family
../metrics/shotgun/Random_forest/bool0001/genus
../metrics/shotgun/Random_forest/bool0001/species
../metrics/shotgun/Random_forest/bool01
../metrics/shotgun/Random_forest/bool01/order
../metrics/shotgun/Random_forest/bool01/family
../metrics/shotgun/Random_forest/bool01/genus
../metrics/shotgun/Random_forest/bool01/species
../metrics/shotgun/svm
../metrics/shotgun/svm/bool0
../metrics/shotgun/svm/bool0/order
../metrics/shotgun/svm/bool0/family
../metrics/shotgun/svm/bool0/genus
../metrics/shotgun/svm/bool0/species
../metrics/shotgun/svm/abundance
../metrics/shotgun/svm/abundance/order
../metrics/shotgun/svm/abundance/family
../metrics/shotgun/svm/abundance/genus
../metrics/shotgun/svm/abundance/species
../metrics/shotgun/lodo
../metrics/shotgun/lodo/Random_forest
../metrics/shotgun/lodo/Random_forest/bool0
../metrics/shotgun/lodo/Random_forest/bool0/order
../metrics/shotgun/lodo/Random_forest/bool0/family
../metrics/shotgun/lodo/Random_forest/bool0/genus
../metrics/shotgun/lodo/Random_forest/bool0/species
../metrics/shotgun/lodo/Random_forest/abundance
../metrics/shotgun/lodo/Random_forest/abundance/order
../metrics/shotgun/lodo/Random_forest/abundance/family
../metrics/shotgun/lodo/Random_forest/abundance/genus
../metrics/shotgun/lodo/Random_forest/abundance/species
../metrics/shotgun/lodo/Random_forest/bool001
../metrics/shotgun/lodo/Random_forest/bool001/order
../metrics/shotgun/lodo/Random_forest/bool001/family
../metrics/shotgun/lodo/Random_forest/bool001/genus
../metrics/shotgun/lodo/Random_forest/bool001/species
../metrics/shotgun/lodo/Random_forest/bool00001
../metrics/shotgun/lodo/Random_forest/bool00001/order
../metrics/shotgun/lodo/Random_forest/bool00001/family
../metrics/shotgun/lodo/Random_forest/bool00001/genus
../metrics/shotgun/lodo/Random_forest/bool00001/species
../metrics/shotgun/lodo/Random_forest/bool0001
../metrics/shotgun/lodo/Random_forest/bool0001/order
../metrics/shotgun/lodo/Random_forest/bool0001/family
../metrics/shotgun/lodo/Random_forest/bool0001/genus
../metrics/shotgun/lodo/Random_forest/bool0001/species
../metrics/shotgun/lodo/Random_forest/bool01
../metrics/shotgun/lodo/Random_forest/bool01/order
../metrics/shotgun/lodo/Random_forest/bool01/family
../metrics/shotgun/lodo/Random_forest/bool01/genus
../metrics/shotgun/lodo/Random_forest/bool01/species
../metrics/shotgun/lasso
../metrics/shotgun/lasso/bool0
../metrics/shotgun/lasso/bool0/order
../metrics/shotgun/lasso/bool0/family
../metrics/shotgun/lasso/bool0/genus
../metrics/shotgun/lasso/bool0/species
../metrics/shotgun/lasso/abundance
../metrics/shotgun/lasso/abundance/order
../metrics/shotgun/lasso/abundance/family
../metrics/shotgun/lasso/abundance/genus
../metrics/shotgun/lasso/abundance/species
../metrics/test
../metrics/test/16s
../metrics/test/16s/Random_forest
../metrics/test/16s/Random_forest/bool0
../metrics/test/shotgun
../metrics/test/shotgun/enet
../metrics/test/shotgun/enet/bool0
../metrics/test/shotgun/enet/bool0/order
../metrics/test/shotgun/enet/bool0/family
../metrics/test/shotgun/enet/bool0/genus
../metrics/test/shotgun/enet/bool0/species
../metrics/test/shotgun/enet/abundance
../metrics/test/shotgun/enet/abundance/order
../metrics/test/shotgun/enet/abundance/family
../metrics/test/shotgun/enet/abundance/genus
../metrics/test/shotgun/enet/abundance/species
../metrics/test/shotgun/lsvm
../metrics/test/shotgun/lsvm/bool0
../metrics/test/shotgun/lsvm/bool0/order
../metrics/test/shotgun/lsvm/bool0/family
../metrics/test/shotgun/lsvm/bool0/genus
../metrics/test/shotgun/lsvm/bool0/species
../metrics/test/shotgun/lsvm/abundance
../metrics/test/shotgun/lsvm/abundance/order
../metrics/test/shotgun/lsvm/abundance/family
../metrics/test/shotgun/lsvm/abundance/genus
../metrics/test/shotgun/lsvm/abundance/species
../metrics/test/shotgun/Random_forest
../metrics/test/shotgun/Random_forest/bool0
../metrics/test/shotgun/Random_forest/bool0/order
../metrics/test/shotgun/Random_forest/bool0/family
../metrics/test/shotgun/Random_forest/bool0/genus
../metrics/test/shotgun/Random_forest/bool0/species
../metrics/test/shotgun/Random_forest/order
../metrics/test/shotgun/Random_forest/family
../metrics/test/shotgun/Random_forest/genus
../metrics/test/shotgun/Random_forest/bool001
../metrics/test/shotgun/Random_forest/bool001/order
../metrics/test/shotgun/Random_forest/bool001/family
../metrics/test/shotgun/Random_forest/bool001/genus
../metrics/test/shotgun/Random_forest/bool001/species
../metrics/test/shotgun/Random_forest/bool00001
../metrics/test/shotgun/Random_forest/bool00001/order
../metrics/test/shotgun/Random_forest/bool00001/family
../metrics/test/shotgun/Random_forest/bool00001/genus
../metrics/test/shotgun/Random_forest/bool00001/species
../metrics/test/shotgun/Random_forest/bool0001
../metrics/test/shotgun/Random_forest/bool0001/order
../metrics/test/shotgun/Random_forest/bool0001/family
../metrics/test/shotgun/Random_forest/bool0001/genus
../metrics/test/shotgun/Random_forest/bool0001/species
../metrics/test/shotgun/Random_forest/bool01
../metrics/test/shotgun/Random_forest/bool01/order
../metrics/test/shotgun/Random_forest/bool01/family
../metrics/test/shotgun/Random_forest/bool01/genus
../metrics/test/shotgun/Random_forest/bool01/species
../metrics/test/shotgun/svm
../metrics/test/shotgun/svm/abundance
../metrics/test/shotgun/svm/abundance/order
../metrics/test/shotgun/svm/abundance/family
../metrics/test/shotgun/svm/abundance/genus
../metrics/test/shotgun/svm/abundance/species
../metrics/test/shotgun/lodo
../metrics/test/shotgun/lodo/Random_forest
../metrics/test/shotgun/lodo/Random_forest/bool0
../metrics/test/shotgun/lodo/Random_forest/bool0/order
../metrics/test/shotgun/lodo/Random_forest/bool0/family
../metrics/test/shotgun/lodo/Random_forest/bool0/genus
../metrics/test/shotgun/lodo/Random_forest/bool0/species
../metrics/test/shotgun/lodo/Random_forest/bool001
../metrics/test/shotgun/lodo/Random_forest/bool001/order
../metrics/test/shotgun/lodo/Random_forest/bool001/family
../metrics/test/shotgun/lodo/Random_forest/bool001/genus
../metrics/test/shotgun/lodo/Random_forest/bool001/species
../metrics/test/shotgun/lodo/Random_forest/bool00001
../metrics/test/shotgun/lodo/Random_forest/bool00001/order
../metrics/test/shotgun/lodo/Random_forest/bool00001/family
../metrics/test/shotgun/lodo/Random_forest/bool00001/genus
../metrics/test/shotgun/lodo/Random_forest/bool00001/species
../metrics/test/shotgun/lodo/Random_forest/bool0001
../metrics/test/shotgun/lodo/Random_forest/bool0001/order
../metrics/test/shotgun/lodo/Random_forest/bool0001/family
../metrics/test/shotgun/lodo/Random_forest/bool0001/genus
../metrics/test/shotgun/lodo/Random_forest/bool0001/species
../metrics/test/shotgun/lodo/Random_forest/bool01
../metrics/test/shotgun/lodo/Random_forest/bool01/order
../metrics/test/shotgun/lodo/Random_forest/bool01/family
../metrics/test/shotgun/lodo/Random_forest/bool01/genus
../metrics/test/shotgun/lodo/Random_forest/bool01/species
../code
../results
../results/classification
../results/classification/16s
../results/classification/16s/enet
../results/classification/16s/enet/bool0
../results/classification/16s/enet/bool0/order
../results/classification/16s/enet/bool0/family
../results/classification/16s/enet/bool0/genus
../results/classification/16s/enet/bool0/species
../results/classification/16s/enet/abundance
../results/classification/16s/enet/abundance/order
../results/classification/16s/enet/abundance/family
../results/classification/16s/enet/abundance/genus
../results/classification/16s/enet/abundance/species
../results/classification/16s/lsvm
../results/classification/16s/lsvm/bool0
../results/classification/16s/lsvm/bool0/order
../results/classification/16s/lsvm/bool0/family
../results/classification/16s/lsvm/bool0/genus
../results/classification/16s/lsvm/bool0/species
../results/classification/16s/lsvm/abundance
../results/classification/16s/lsvm/abundance/order
../results/classification/16s/lsvm/abundance/family
../results/classification/16s/lsvm/abundance/genus
../results/classification/16s/lsvm/abundance/species
../results/classification/16s/Random_forest
../results/classification/16s/Random_forest/bool0
../results/classification/16s/Random_forest/bool0/order
../results/classification/16s/Random_forest/bool0/family
../results/classification/16s/Random_forest/bool0/genus
../results/classification/16s/Random_forest/bool0/species
../results/classification/16s/Random_forest/abundance
../results/classification/16s/Random_forest/abundance/order
../results/classification/16s/Random_forest/abundance/family
../results/classification/16s/Random_forest/abundance/genus
../results/classification/16s/Random_forest/abundance/species
../results/classification/16s/svm
../results/classification/16s/svm/bool0
../results/classification/16s/svm/bool0/order
../results/classification/16s/svm/bool0/family
../results/classification/16s/svm/bool0/genus
../results/classification/16s/svm/bool0/species
../results/classification/16s/svm/abundance
../results/classification/16s/svm/abundance/order
../results/classification/16s/svm/abundance/family
../results/classification/16s/svm/abundance/genus
../results/classification/16s/svm/abundance/species
../results/classification/16s/lasso
../results/classification/16s/lasso/bool0
../results/classification/16s/lasso/bool0/order
../results/classification/16s/lasso/bool0/family
../results/classification/16s/lasso/bool0/genus
../results/classification/16s/lasso/bool0/species
../results/classification/16s/lasso/abundance
../results/classification/16s/lasso/abundance/order
../results/classification/16s/lasso/abundance/family
../results/classification/16s/lasso/abundance/genus
../results/classification/16s/lasso/abundance/species
../results/classification/shotgun
../results/classification/shotgun/enet
../results/classification/shotgun/enet/bool0
../results/classification/shotgun/enet/bool0/order
../results/classification/shotgun/enet/bool0/family
../results/classification/shotgun/enet/bool0/genus
../results/classification/shotgun/enet/bool0/species
../results/classification/shotgun/enet/abundance
../results/classification/shotgun/enet/abundance/order
../results/classification/shotgun/enet/abundance/family
../results/classification/shotgun/enet/bool001
../results/classification/shotgun/enet/bool001/order
../results/classification/shotgun/enet/bool001/family
../results/classification/shotgun/enet/bool001/genus
../results/classification/shotgun/enet/bool001/species
../results/classification/shotgun/enet/bool00001
../results/classification/shotgun/enet/bool00001/order
../results/classification/shotgun/enet/bool00001/family
../results/classification/shotgun/enet/bool00001/genus
../results/classification/shotgun/enet/bool00001/species
../results/classification/shotgun/enet/bool0001
../results/classification/shotgun/enet/bool0001/order
../results/classification/shotgun/enet/bool0001/family
../results/classification/shotgun/enet/bool0001/genus
../results/classification/shotgun/enet/bool0001/species
../results/classification/shotgun/enet/bool01
../results/classification/shotgun/enet/bool01/order
../results/classification/shotgun/enet/bool01/family
../results/classification/shotgun/enet/bool01/genus
../results/classification/shotgun/enet/bool01/species
../results/classification/shotgun/lsvm
../results/classification/shotgun/lsvm/bool0
../results/classification/shotgun/lsvm/bool0/order
../results/classification/shotgun/lsvm/bool0/family
../results/classification/shotgun/lsvm/bool0/genus
../results/classification/shotgun/lsvm/bool0/species
../results/classification/shotgun/lsvm/abundance
../results/classification/shotgun/lsvm/abundance/family
../results/classification/shotgun/lsvm/bool001
../results/classification/shotgun/lsvm/bool001/order
../results/classification/shotgun/lsvm/bool001/family
../results/classification/shotgun/lsvm/bool001/genus
../results/classification/shotgun/lsvm/bool001/species
../results/classification/shotgun/lsvm/bool00001
../results/classification/shotgun/lsvm/bool00001/order
../results/classification/shotgun/lsvm/bool00001/family
../results/classification/shotgun/lsvm/bool00001/genus
../results/classification/shotgun/lsvm/bool00001/species
../results/classification/shotgun/lsvm/bool0001
../results/classification/shotgun/lsvm/bool0001/order
../results/classification/shotgun/lsvm/bool0001/family
../results/classification/shotgun/lsvm/bool0001/genus
../results/classification/shotgun/lsvm/bool0001/species
../results/classification/shotgun/lsvm/bool01
../results/classification/shotgun/lsvm/bool01/order
../results/classification/shotgun/lsvm/bool01/family
../results/classification/shotgun/lsvm/bool01/genus
../results/classification/shotgun/lsvm/bool01/species
../results/classification/shotgun/Random_forest
../results/classification/shotgun/Random_forest/bool0
../results/classification/shotgun/Random_forest/bool0/order
../results/classification/shotgun/Random_forest/bool0/family
../results/classification/shotgun/Random_forest/bool0/genus
../results/classification/shotgun/Random_forest/bool0/species
../results/classification/shotgun/Random_forest/abundance
../results/classification/shotgun/Random_forest/abundance/order
../results/classification/shotgun/Random_forest/abundance/family
../results/classification/shotgun/Random_forest/abundance/genus
../results/classification/shotgun/Random_forest/abundance/species
../results/classification/shotgun/Random_forest/bool001
../results/classification/shotgun/Random_forest/bool001/order
../results/classification/shotgun/Random_forest/bool001/family
../results/classification/shotgun/Random_forest/bool001/genus
../results/classification/shotgun/Random_forest/bool001/species
../results/classification/shotgun/Random_forest/bool00001
../results/classification/shotgun/Random_forest/bool00001/order
../results/classification/shotgun/Random_forest/bool00001/family
../results/classification/shotgun/Random_forest/bool00001/genus
../results/classification/shotgun/Random_forest/bool00001/species
../results/classification/shotgun/Random_forest/bool0001
../results/classification/shotgun/Random_forest/bool0001/order
../results/classification/shotgun/Random_forest/bool0001/family
../results/classification/shotgun/Random_forest/bool0001/genus
../results/classification/shotgun/Random_forest/bool0001/species
../results/classification/shotgun/Random_forest/bool01
../results/classification/shotgun/Random_forest/bool01/order
../results/classification/shotgun/Random_forest/bool01/family
../results/classification/shotgun/Random_forest/bool01/genus
../results/classification/shotgun/Random_forest/bool01/species
../results/classification/shotgun/svm
../results/classification/shotgun/svm/bool0
../results/classification/shotgun/svm/bool0/order
../results/classification/shotgun/svm/bool0/family
../results/classification/shotgun/svm/bool0/genus
../results/classification/shotgun/svm/bool0/species
../results/classification/shotgun/svm/abundance
../results/classification/shotgun/svm/abundance/family
../results/classification/shotgun/svm/bool001
../results/classification/shotgun/svm/bool001/order
../results/classification/shotgun/svm/bool001/family
../results/classification/shotgun/svm/bool001/genus
../results/classification/shotgun/svm/bool001/species
../results/classification/shotgun/svm/bool00001
../results/classification/shotgun/svm/bool00001/order
../results/classification/shotgun/svm/bool00001/family
../results/classification/shotgun/svm/bool00001/genus
../results/classification/shotgun/svm/bool00001/species
../results/classification/shotgun/svm/bool0001
../results/classification/shotgun/svm/bool0001/order
../results/classification/shotgun/svm/bool0001/family
../results/classification/shotgun/svm/bool0001/genus
../results/classification/shotgun/svm/bool0001/species
../results/classification/shotgun/svm/bool01
../results/classification/shotgun/svm/bool01/order
../results/classification/shotgun/svm/bool01/family
../results/classification/shotgun/svm/bool01/genus
../results/classification/shotgun/svm/bool01/species
../results/classification/shotgun/lodo
../results/classification/shotgun/lodo/enet
../results/classification/shotgun/lodo/enet/bool0
../results/classification/shotgun/lodo/enet/bool0/order
../results/classification/shotgun/lodo/enet/bool0/family
../results/classification/shotgun/lodo/enet/bool0/genus
../results/classification/shotgun/lodo/enet/bool0/species
../results/classification/shotgun/lodo/enet/abundance
../results/classification/shotgun/lodo/enet/abundance/order
../results/classification/shotgun/lodo/enet/abundance/family
../results/classification/shotgun/lodo/enet/bool001
../results/classification/shotgun/lodo/enet/bool001/order
../results/classification/shotgun/lodo/enet/bool001/family
../results/classification/shotgun/lodo/enet/bool001/genus
../results/classification/shotgun/lodo/enet/bool001/species
../results/classification/shotgun/lodo/enet/bool00001
../results/classification/shotgun/lodo/enet/bool00001/order
../results/classification/shotgun/lodo/enet/bool00001/family
../results/classification/shotgun/lodo/enet/bool00001/genus
../results/classification/shotgun/lodo/enet/bool00001/species
../results/classification/shotgun/lodo/enet/bool0001
../results/classification/shotgun/lodo/enet/bool0001/order
../results/classification/shotgun/lodo/enet/bool0001/family
../results/classification/shotgun/lodo/enet/bool0001/genus
../results/classification/shotgun/lodo/enet/bool0001/species
../results/classification/shotgun/lodo/enet/bool01
../results/classification/shotgun/lodo/enet/bool01/order
../results/classification/shotgun/lodo/enet/bool01/family
../results/classification/shotgun/lodo/enet/bool01/genus
../results/classification/shotgun/lodo/enet/bool01/species
../results/classification/shotgun/lodo/lsvm
../results/classification/shotgun/lodo/lsvm/bool0
../results/classification/shotgun/lodo/lsvm/bool0/order
../results/classification/shotgun/lodo/lsvm/bool0/family
../results/classification/shotgun/lodo/lsvm/bool0/genus
../results/classification/shotgun/lodo/lsvm/bool0/species
../results/classification/shotgun/lodo/lsvm/abundance
../results/classification/shotgun/lodo/lsvm/abundance/order
../results/classification/shotgun/lodo/lsvm/abundance/family
../results/classification/shotgun/lodo/lsvm/bool001
../results/classification/shotgun/lodo/lsvm/bool001/order
../results/classification/shotgun/lodo/lsvm/bool001/family
../results/classification/shotgun/lodo/lsvm/bool001/genus
../results/classification/shotgun/lodo/lsvm/bool001/species
../results/classification/shotgun/lodo/lsvm/bool00001
../results/classification/shotgun/lodo/lsvm/bool00001/order
../results/classification/shotgun/lodo/lsvm/bool00001/family
../results/classification/shotgun/lodo/lsvm/bool00001/genus
../results/classification/shotgun/lodo/lsvm/bool00001/species
../results/classification/shotgun/lodo/lsvm/bool0001
../results/classification/shotgun/lodo/lsvm/bool0001/order
../results/classification/shotgun/lodo/lsvm/bool0001/family
../results/classification/shotgun/lodo/lsvm/bool0001/genus
../results/classification/shotgun/lodo/lsvm/bool0001/species
../results/classification/shotgun/lodo/lsvm/bool01
../results/classification/shotgun/lodo/lsvm/bool01/order
../results/classification/shotgun/lodo/lsvm/bool01/family
../results/classification/shotgun/lodo/lsvm/bool01/genus
../results/classification/shotgun/lodo/lsvm/bool01/species
../results/classification/shotgun/lodo/Random_forest
../results/classification/shotgun/lodo/Random_forest/bool0
../results/classification/shotgun/lodo/Random_forest/bool0/order
../results/classification/shotgun/lodo/Random_forest/bool0/family
../results/classification/shotgun/lodo/Random_forest/bool0/genus
../results/classification/shotgun/lodo/Random_forest/bool0/species
../results/classification/shotgun/lodo/Random_forest/abundance
../results/classification/shotgun/lodo/Random_forest/abundance/order
../results/classification/shotgun/lodo/Random_forest/abundance/family
../results/classification/shotgun/lodo/Random_forest/bool001
../results/classification/shotgun/lodo/Random_forest/bool001/order
../results/classification/shotgun/lodo/Random_forest/bool001/family
../results/classification/shotgun/lodo/Random_forest/bool001/genus
../results/classification/shotgun/lodo/Random_forest/bool001/species
../results/classification/shotgun/lodo/Random_forest/bool00001
../results/classification/shotgun/lodo/Random_forest/bool00001/order
../results/classification/shotgun/lodo/Random_forest/bool00001/family
../results/classification/shotgun/lodo/Random_forest/bool00001/genus
../results/classification/shotgun/lodo/Random_forest/bool00001/species
../results/classification/shotgun/lodo/Random_forest/bool0001
../results/classification/shotgun/lodo/Random_forest/bool0001/order
../results/classification/shotgun/lodo/Random_forest/bool0001/family
../results/classification/shotgun/lodo/Random_forest/bool0001/genus
../results/classification/shotgun/lodo/Random_forest/bool0001/species
../results/classification/shotgun/lodo/Random_forest/bool01
../results/classification/shotgun/lodo/Random_forest/bool01/order
../results/classification/shotgun/lodo/Random_forest/bool01/family
../results/classification/shotgun/lodo/Random_forest/bool01/genus
../results/classification/shotgun/lodo/Random_forest/bool01/species
../results/classification/shotgun/lodo/svm
../results/classification/shotgun/lodo/svm/bool0
../results/classification/shotgun/lodo/svm/bool0/order
../results/classification/shotgun/lodo/svm/bool0/family
../results/classification/shotgun/lodo/svm/bool0/genus
../results/classification/shotgun/lodo/svm/bool0/species
../results/classification/shotgun/lodo/svm/abundance
../results/classification/shotgun/lodo/svm/abundance/order
../results/classification/shotgun/lodo/svm/abundance/family
../results/classification/shotgun/lodo/svm/bool001
../results/classification/shotgun/lodo/svm/bool001/order
../results/classification/shotgun/lodo/svm/bool001/family
../results/classification/shotgun/lodo/svm/bool001/genus
../results/classification/shotgun/lodo/svm/bool001/species
../results/classification/shotgun/lodo/svm/bool00001
../results/classification/shotgun/lodo/svm/bool00001/order
../results/classification/shotgun/lodo/svm/bool00001/family
../results/classification/shotgun/lodo/svm/bool00001/genus
../results/classification/shotgun/lodo/svm/bool00001/species
../results/classification/shotgun/lodo/svm/bool0001
../results/classification/shotgun/lodo/svm/bool0001/order
../results/classification/shotgun/lodo/svm/bool0001/family
../results/classification/shotgun/lodo/svm/bool0001/genus
../results/classification/shotgun/lodo/svm/bool0001/species
../results/classification/shotgun/lodo/svm/bool01
../results/classification/shotgun/lodo/svm/bool01/order
../results/classification/shotgun/lodo/svm/bool01/family
../results/classification/shotgun/lodo/svm/bool01/genus
../results/classification/shotgun/lodo/svm/bool01/species
../results/classification/shotgun/lodo/lasso
../results/classification/shotgun/lodo/lasso/bool0
../results/classification/shotgun/lodo/lasso/bool0/order
../results/classification/shotgun/lodo/lasso/bool0/family
../results/classification/shotgun/lodo/lasso/bool0/genus
../results/classification/shotgun/lodo/lasso/bool0/species
../results/classification/shotgun/lodo/lasso/abundance
../results/classification/shotgun/lodo/lasso/abundance/order
../results/classification/shotgun/lodo/lasso/abundance/family
../results/classification/shotgun/lodo/lasso/bool001
../results/classification/shotgun/lodo/lasso/bool001/order
../results/classification/shotgun/lodo/lasso/bool001/family
../results/classification/shotgun/lodo/lasso/bool001/genus
../results/classification/shotgun/lodo/lasso/bool001/species
../results/classification/shotgun/lodo/lasso/bool00001
../results/classification/shotgun/lodo/lasso/bool00001/order
../results/classification/shotgun/lodo/lasso/bool00001/family
../results/classification/shotgun/lodo/lasso/bool00001/genus
../results/classification/shotgun/lodo/lasso/bool00001/species
../results/classification/shotgun/lodo/lasso/bool0001
../results/classification/shotgun/lodo/lasso/bool0001/order
../results/classification/shotgun/lodo/lasso/bool0001/family
../results/classification/shotgun/lodo/lasso/bool0001/genus
../results/classification/shotgun/lodo/lasso/bool0001/species
../results/classification/shotgun/lodo/lasso/bool01
../results/classification/shotgun/lodo/lasso/bool01/order
../results/classification/shotgun/lodo/lasso/bool01/family
../results/classification/shotgun/lodo/lasso/bool01/genus
../results/classification/shotgun/lodo/lasso/bool01/species
../results/classification/shotgun/lasso
../results/classification/shotgun/lasso/bool0
../results/classification/shotgun/lasso/bool0/order
../results/classification/shotgun/lasso/bool0/family
../results/classification/shotgun/lasso/bool0/genus
../results/classification/shotgun/lasso/bool0/species
../results/classification/shotgun/lasso/abundance
../results/classification/shotgun/lasso/abundance/order
../results/classification/shotgun/lasso/abundance/family
../results/classification/shotgun/lasso/bool001
../results/classification/shotgun/lasso/bool001/order
../results/classification/shotgun/lasso/bool001/family
../results/classification/shotgun/lasso/bool001/genus
../results/classification/shotgun/lasso/bool001/species
../results/classification/shotgun/lasso/bool00001
../results/classification/shotgun/lasso/bool00001/order
../results/classification/shotgun/lasso/bool00001/family
../results/classification/shotgun/lasso/bool00001/genus
../results/classification/shotgun/lasso/bool00001/species
../results/classification/shotgun/lasso/bool0001
../results/classification/shotgun/lasso/bool0001/order
../results/classification/shotgun/lasso/bool0001/family
../results/classification/shotgun/lasso/bool0001/genus
../results/classification/shotgun/lasso/bool0001/species
../results/classification/shotgun/lasso/bool01
../results/classification/shotgun/lasso/bool01/order
../results/classification/shotgun/lasso/bool01/family
../results/classification/shotgun/lasso/bool01/genus
../results/classification/shotgun/lasso/bool01/species
../results/test
../results/test/16s
../results/test/16s/Random_forest
../results/test/16s/Random_forest/bool0
../results/test/shotgun
../results/test/shotgun/enet
../results/test/shotgun/enet/bool0
../results/test/shotgun/enet/bool0/order
../results/test/shotgun/enet/bool0/family
../results/test/shotgun/enet/bool0/genus
../results/test/shotgun/enet/bool0/species
../results/test/shotgun/enet/bool001
../results/test/shotgun/enet/bool001/order
../results/test/shotgun/enet/bool001/family
../results/test/shotgun/enet/bool001/genus
../results/test/shotgun/enet/bool001/species
../results/test/shotgun/enet/bool00001
../results/test/shotgun/enet/bool00001/order
../results/test/shotgun/enet/bool00001/family
../results/test/shotgun/enet/bool00001/genus
../results/test/shotgun/enet/bool00001/species
../results/test/shotgun/enet/bool0001
../results/test/shotgun/enet/bool0001/order
../results/test/shotgun/enet/bool0001/family
../results/test/shotgun/enet/bool0001/genus
../results/test/shotgun/enet/bool0001/species
../results/test/shotgun/enet/bool01
../results/test/shotgun/enet/bool01/order
../results/test/shotgun/enet/bool01/family
../results/test/shotgun/enet/bool01/genus
../results/test/shotgun/enet/bool01/species
../results/test/shotgun/lsvm
../results/test/shotgun/lsvm/bool0
../results/test/shotgun/lsvm/bool0/order
../results/test/shotgun/lsvm/bool0/family
../results/test/shotgun/lsvm/bool0/genus
../results/test/shotgun/lsvm/bool0/species
../results/test/shotgun/lsvm/bool001
../results/test/shotgun/lsvm/bool001/order
../results/test/shotgun/lsvm/bool001/family
../results/test/shotgun/lsvm/bool001/genus
../results/test/shotgun/lsvm/bool001/species
../results/test/shotgun/lsvm/bool00001
../results/test/shotgun/lsvm/bool00001/order
../results/test/shotgun/lsvm/bool00001/family
../results/test/shotgun/lsvm/bool00001/genus
../results/test/shotgun/lsvm/bool00001/species
../results/test/shotgun/lsvm/bool0001
../results/test/shotgun/lsvm/bool0001/order
../results/test/shotgun/lsvm/bool0001/family
../results/test/shotgun/lsvm/bool0001/genus
../results/test/shotgun/lsvm/bool0001/species
../results/test/shotgun/lsvm/bool01
../results/test/shotgun/lsvm/bool01/order
../results/test/shotgun/lsvm/bool01/family
../results/test/shotgun/lsvm/bool01/genus
../results/test/shotgun/lsvm/bool01/species
../results/test/shotgun/Random_forest
../results/test/shotgun/Random_forest/bool0
../results/test/shotgun/Random_forest/bool0/order
../results/test/shotgun/Random_forest/bool0/family
../results/test/shotgun/Random_forest/bool0/genus
../results/test/shotgun/Random_forest/bool0/species
../results/test/shotgun/Random_forest/order
../results/test/shotgun/Random_forest/family
../results/test/shotgun/Random_forest/genus
../results/test/shotgun/Random_forest/bool001
../results/test/shotgun/Random_forest/bool001/order
../results/test/shotgun/Random_forest/bool001/family
../results/test/shotgun/Random_forest/bool001/genus
../results/test/shotgun/Random_forest/bool001/species
../results/test/shotgun/Random_forest/bool00001
../results/test/shotgun/Random_forest/bool00001/order
../results/test/shotgun/Random_forest/bool00001/family
../results/test/shotgun/Random_forest/bool00001/genus
../results/test/shotgun/Random_forest/bool00001/species
../results/test/shotgun/Random_forest/bool0001
../results/test/shotgun/Random_forest/bool0001/order
../results/test/shotgun/Random_forest/bool0001/family
../results/test/shotgun/Random_forest/bool0001/genus
../results/test/shotgun/Random_forest/bool0001/species
../results/test/shotgun/Random_forest/bool01
../results/test/shotgun/Random_forest/bool01/order
../results/test/shotgun/Random_forest/bool01/family
../results/test/shotgun/Random_forest/bool01/genus
../results/test/shotgun/Random_forest/bool01/species
../results/test/shotgun/svm
../results/test/shotgun/svm/bool0
../results/test/shotgun/svm/bool0/order
../results/test/shotgun/svm/bool0/family
../results/test/shotgun/svm/bool0/genus
../results/test/shotgun/svm/bool0/species
../results/test/shotgun/svm/bool001
../results/test/shotgun/svm/bool001/order
../results/test/shotgun/svm/bool001/family
../results/test/shotgun/svm/bool001/genus
../results/test/shotgun/svm/bool001/species
../results/test/shotgun/svm/bool00001
../results/test/shotgun/svm/bool00001/order
../results/test/shotgun/svm/bool00001/family
../results/test/shotgun/svm/bool00001/genus
../results/test/shotgun/svm/bool00001/species
../results/test/shotgun/svm/bool0001
../results/test/shotgun/svm/bool0001/order
../results/test/shotgun/svm/bool0001/family
../results/test/shotgun/svm/bool0001/genus
../results/test/shotgun/svm/bool0001/species
../results/test/shotgun/svm/bool01
../results/test/shotgun/svm/bool01/order
../results/test/shotgun/svm/bool01/family
../results/test/shotgun/svm/bool01/genus
../results/test/shotgun/svm/bool01/species
../results/test/shotgun/lodo
../results/test/shotgun/lodo/enet
../results/test/shotgun/lodo/enet/bool0
../results/test/shotgun/lodo/enet/bool0/order
../results/test/shotgun/lodo/enet/bool0/family
../results/test/shotgun/lodo/enet/bool0/genus
../results/test/shotgun/lodo/enet/bool0/species
../results/test/shotgun/lodo/enet/bool001
../results/test/shotgun/lodo/enet/bool001/order
../results/test/shotgun/lodo/enet/bool001/family
../results/test/shotgun/lodo/enet/bool001/genus
../results/test/shotgun/lodo/enet/bool001/species
../results/test/shotgun/lodo/enet/bool00001
../results/test/shotgun/lodo/enet/bool00001/order
../results/test/shotgun/lodo/enet/bool00001/family
../results/test/shotgun/lodo/enet/bool00001/genus
../results/test/shotgun/lodo/enet/bool00001/species
../results/test/shotgun/lodo/enet/bool0001
../results/test/shotgun/lodo/enet/bool0001/order
../results/test/shotgun/lodo/enet/bool0001/family
../results/test/shotgun/lodo/enet/bool0001/genus
../results/test/shotgun/lodo/enet/bool0001/species
../results/test/shotgun/lodo/enet/bool01
../results/test/shotgun/lodo/enet/bool01/order
../results/test/shotgun/lodo/enet/bool01/family
../results/test/shotgun/lodo/enet/bool01/genus
../results/test/shotgun/lodo/enet/bool01/species
../results/test/shotgun/lodo/lsvm
../results/test/shotgun/lodo/lsvm/bool0
../results/test/shotgun/lodo/lsvm/bool0/order
../results/test/shotgun/lodo/lsvm/bool0/family
../results/test/shotgun/lodo/lsvm/bool0/genus
../results/test/shotgun/lodo/lsvm/bool0/species
../results/test/shotgun/lodo/lsvm/bool001
../results/test/shotgun/lodo/lsvm/bool001/order
../results/test/shotgun/lodo/lsvm/bool001/family
../results/test/shotgun/lodo/lsvm/bool001/genus
../results/test/shotgun/lodo/lsvm/bool001/species
../results/test/shotgun/lodo/lsvm/bool00001
../results/test/shotgun/lodo/lsvm/bool00001/order
../results/test/shotgun/lodo/lsvm/bool00001/family
../results/test/shotgun/lodo/lsvm/bool00001/genus
../results/test/shotgun/lodo/lsvm/bool00001/species
../results/test/shotgun/lodo/lsvm/bool0001
../results/test/shotgun/lodo/lsvm/bool0001/order
../results/test/shotgun/lodo/lsvm/bool0001/family
../results/test/shotgun/lodo/lsvm/bool0001/genus
../results/test/shotgun/lodo/lsvm/bool0001/species
../results/test/shotgun/lodo/lsvm/bool01
../results/test/shotgun/lodo/lsvm/bool01/order
../results/test/shotgun/lodo/lsvm/bool01/family
../results/test/shotgun/lodo/lsvm/bool01/genus
../results/test/shotgun/lodo/lsvm/bool01/species
../results/test/shotgun/lodo/Random_forest
../results/test/shotgun/lodo/Random_forest/bool0
../results/test/shotgun/lodo/Random_forest/bool0/order
../results/test/shotgun/lodo/Random_forest/bool0/family
../results/test/shotgun/lodo/Random_forest/bool0/genus
../results/test/shotgun/lodo/Random_forest/bool0/species
../results/test/shotgun/lodo/Random_forest/bool001
../results/test/shotgun/lodo/Random_forest/bool001/order
../results/test/shotgun/lodo/Random_forest/bool001/family
../results/test/shotgun/lodo/Random_forest/bool001/genus
../results/test/shotgun/lodo/Random_forest/bool001/species
../results/test/shotgun/lodo/Random_forest/bool00001
../results/test/shotgun/lodo/Random_forest/bool00001/order
../results/test/shotgun/lodo/Random_forest/bool00001/family
../results/test/shotgun/lodo/Random_forest/bool00001/genus
../results/test/shotgun/lodo/Random_forest/bool00001/species
../results/test/shotgun/lodo/Random_forest/bool0001
../results/test/shotgun/lodo/Random_forest/bool0001/order
../results/test/shotgun/lodo/Random_forest/bool0001/family
../results/test/shotgun/lodo/Random_forest/bool0001/genus
../results/test/shotgun/lodo/Random_forest/bool0001/species
../results/test/shotgun/lodo/Random_forest/bool01
../results/test/shotgun/lodo/Random_forest/bool01/order
../results/test/shotgun/lodo/Random_forest/bool01/family
../results/test/shotgun/lodo/Random_forest/bool01/genus
../results/test/shotgun/lodo/Random_forest/bool01/species
../results/test/shotgun/lodo/svm
../results/test/shotgun/lodo/svm/bool0
../results/test/shotgun/lodo/svm/bool0/order
../results/test/shotgun/lodo/svm/bool0/family
../results/test/shotgun/lodo/svm/bool0/genus
../results/test/shotgun/lodo/svm/bool0/species
../results/test/shotgun/lodo/svm/bool001
../results/test/shotgun/lodo/svm/bool001/order
../results/test/shotgun/lodo/svm/bool001/family
../results/test/shotgun/lodo/svm/bool001/genus
../results/test/shotgun/lodo/svm/bool001/species
../results/test/shotgun/lodo/svm/bool00001
../results/test/shotgun/lodo/svm/bool00001/order
../results/test/shotgun/lodo/svm/bool00001/family
../results/test/shotgun/lodo/svm/bool00001/genus
../results/test/shotgun/lodo/svm/bool00001/species
../results/test/shotgun/lodo/svm/bool0001
../results/test/shotgun/lodo/svm/bool0001/order
../results/test/shotgun/lodo/svm/bool0001/family
../results/test/shotgun/lodo/svm/bool0001/genus
../results/test/shotgun/lodo/svm/bool0001/species
../results/test/shotgun/lodo/svm/bool01
../results/test/shotgun/lodo/svm/bool01/order
../results/test/shotgun/lodo/svm/bool01/family
../results/test/shotgun/lodo/svm/bool01/genus
../results/test/shotgun/lodo/svm/bool01/species
../results/test/shotgun/lodo/lasso
../results/test/shotgun/lodo/lasso/bool0
../results/test/shotgun/lodo/lasso/bool0/order
../results/test/shotgun/lodo/lasso/bool0/family
../results/test/shotgun/lodo/lasso/bool0/genus
../results/test/shotgun/lodo/lasso/bool0/species
../results/test/shotgun/lodo/lasso/bool001
../results/test/shotgun/lodo/lasso/bool001/order
../results/test/shotgun/lodo/lasso/bool001/family
../results/test/shotgun/lodo/lasso/bool001/genus
../results/test/shotgun/lodo/lasso/bool001/species
../results/test/shotgun/lodo/lasso/bool00001
../results/test/shotgun/lodo/lasso/bool00001/order
../results/test/shotgun/lodo/lasso/bool00001/family
../results/test/shotgun/lodo/lasso/bool00001/genus
../results/test/shotgun/lodo/lasso/bool00001/species
../results/test/shotgun/lodo/lasso/bool0001
../results/test/shotgun/lodo/lasso/bool0001/order
../results/test/shotgun/lodo/lasso/bool0001/family
../results/test/shotgun/lodo/lasso/bool0001/genus
../results/test/shotgun/lodo/lasso/bool0001/species
../results/test/shotgun/lodo/lasso/bool01
../results/test/shotgun/lodo/lasso/bool01/order
../results/test/shotgun/lodo/lasso/bool01/family
../results/test/shotgun/lodo/lasso/bool01/genus
../results/test/shotgun/lodo/lasso/bool01/species
../results/test/shotgun/lasso
../results/test/shotgun/lasso/bool0
../results/test/shotgun/lasso/bool0/order
../results/test/shotgun/lasso/bool0/family
../results/test/shotgun/lasso/bool0/genus
../results/test/shotgun/lasso/bool0/species
../results/test/shotgun/lasso/bool001
../results/test/shotgun/lasso/bool001/order
../results/test/shotgun/lasso/bool001/family
../results/test/shotgun/lasso/bool001/genus
../results/test/shotgun/lasso/bool001/species
../results/test/shotgun/lasso/bool00001
../results/test/shotgun/lasso/bool00001/order
../results/test/shotgun/lasso/bool00001/family
../results/test/shotgun/lasso/bool00001/genus
../results/test/shotgun/lasso/bool00001/species
../results/test/shotgun/lasso/bool0001
../results/test/shotgun/lasso/bool0001/order
../results/test/shotgun/lasso/bool0001/family
../results/test/shotgun/lasso/bool0001/genus
../results/test/shotgun/lasso/bool0001/species
../results/test/shotgun/lasso/bool01
../results/test/shotgun/lasso/bool01/order
../results/test/shotgun/lasso/bool01/family
../results/test/shotgun/lasso/bool01/genus
../results/test/shotgun/lasso/bool01/species
../results/biomarkers
../results/biomarkers/16s
../results/biomarkers/16s/bool0
../results/biomarkers/16s/abundance
../results/biomarkers/shotgun
../results/biomarkers/shotgun/bool0
../results/biomarkers/shotgun/bool0/order
../results/biomarkers/shotgun/bool0/family
../results/biomarkers/shotgun/bool0/genus
../results/biomarkers/shotgun/bool0/species
../results/biomarkers/shotgun/abundance
../results/biomarkers/shotgun/abundance/order
../results/biomarkers/shotgun/abundance/family
../results/biomarkers/shotgun/abundance/genus
../results/biomarkers/shotgun/abundance/species
../results/biomarkers/shotgun/bool001
../results/biomarkers/shotgun/bool001/order
../results/biomarkers/shotgun/bool001/family
../results/biomarkers/shotgun/bool001/genus
../results/biomarkers/shotgun/bool001/species
../results/biomarkers/shotgun/lodo
../results/biomarkers/shotgun/lodo/bool0
../results/biomarkers/shotgun/lodo/bool0/order
../results/biomarkers/shotgun/lodo/bool0/family
../results/biomarkers/shotgun/lodo/bool0/genus
../results/biomarkers/shotgun/lodo/bool0/species
../results/biomarkers/shotgun/lodo/abundance
../results/biomarkers/shotgun/lodo/abundance/order
../results/biomarkers/shotgun/lodo/abundance/family
../results/biomarkers/shotgun/lodo/abundance/genus
../results/biomarkers/shotgun/lodo/abundance/species
../results/biomarkers/shotgun/lodo/bool001
../results/biomarkers/shotgun/lodo/bool001/order
../results/biomarkers/shotgun/lodo/bool001/family
../results/biomarkers/shotgun/lodo/bool001/genus
../results/biomarkers/shotgun/lodo/bool001/species
../results/biomarkers/shotgun/lodo/bool00001
../results/biomarkers/shotgun/lodo/bool00001/order
../results/biomarkers/shotgun/lodo/bool00001/family
../results/biomarkers/shotgun/lodo/bool00001/genus
../results/biomarkers/shotgun/lodo/bool00001/species
../results/biomarkers/shotgun/lodo/bool0001
../results/biomarkers/shotgun/lodo/bool0001/order
../results/biomarkers/shotgun/lodo/bool0001/family
../results/biomarkers/shotgun/lodo/bool0001/genus
../results/biomarkers/shotgun/lodo/bool0001/species
../results/biomarkers/shotgun/lodo/bool01
../results/biomarkers/shotgun/lodo/bool01/order
../results/biomarkers/shotgun/lodo/bool01/family
../results/biomarkers/shotgun/lodo/bool01/genus
../results/biomarkers/shotgun/lodo/bool01/species
../results/biomarkers/shotgun/bool00001
../results/biomarkers/shotgun/bool00001/order
../results/biomarkers/shotgun/bool00001/family
../results/biomarkers/shotgun/bool00001/genus
../results/biomarkers/shotgun/bool00001/species
../results/biomarkers/shotgun/bool0001
../results/biomarkers/shotgun/bool0001/order
../results/biomarkers/shotgun/bool0001/family
../results/biomarkers/shotgun/bool0001/genus
../results/biomarkers/shotgun/bool0001/species
../results/biomarkers/shotgun/bool01
../results/biomarkers/shotgun/bool01/order
../results/biomarkers/shotgun/bool01/family
../results/biomarkers/shotgun/bool01/genus
../results/biomarkers/shotgun/bool01/species
../results/fig_and_tables
../data
../data/16s
../data/16s/bool0
../data/16s/abundance
../data/shotgun
../data/shotgun/bool0
../data/shotgun/bool0/order
../data/shotgun/bool0/family
../data/shotgun/bool0/genus
../data/shotgun/bool0/species
../data/shotgun/abundance
../data/shotgun/abundance/order
../data/shotgun/abundance/family
../data/shotgun/abundance/genus
../data/shotgun/abundance/species
../data/shotgun/bool001
../data/shotgun/bool001/order
../data/shotgun/bool001/family
../data/shotgun/bool001/genus
../data/shotgun/bool001/species
../data/shotgun/lodo
../data/shotgun/lodo/bool0
../data/shotgun/lodo/bool0/order
../data/shotgun/lodo/bool0/family
../data/shotgun/lodo/bool0/genus
../data/shotgun/lodo/bool0/species
../data/shotgun/lodo/abundance
../data/shotgun/lodo/abundance/order
../data/shotgun/lodo/abundance/family
../data/shotgun/lodo/abundance/genus
../data/shotgun/lodo/abundance/species
../data/shotgun/lodo/bool001
../data/shotgun/lodo/bool001/order
../data/shotgun/lodo/bool001/family
../data/shotgun/lodo/bool001/genus
../data/shotgun/lodo/bool001/species
../data/shotgun/lodo/bool00001
../data/shotgun/lodo/bool00001/order
../data/shotgun/lodo/bool00001/family
../data/shotgun/lodo/bool00001/genus
../data/shotgun/lodo/bool00001/species
../data/shotgun/lodo/bool0001
../data/shotgun/lodo/bool0001/order
../data/shotgun/lodo/bool0001/family
../data/shotgun/lodo/bool0001/genus
../data/shotgun/lodo/bool0001/species
../data/shotgun/lodo/bool01
../data/shotgun/lodo/bool01/order
../data/shotgun/lodo/bool01/family
../data/shotgun/lodo/bool01/genus
../data/shotgun/lodo/bool01/species
../data/shotgun/bool00001
../data/shotgun/bool00001/order
../data/shotgun/bool00001/family
../data/shotgun/bool00001/genus
../data/shotgun/bool00001/species
../data/shotgun/bool0001
../data/shotgun/bool0001/order
../data/shotgun/bool0001/family
../data/shotgun/bool0001/genus
../data/shotgun/bool0001/species
../data/shotgun/bool01
../data/shotgun/bool01/order
../data/shotgun/bool01/family
../data/shotgun/bool01/genus
../data/shotgun/bool01/species
)

for i in ${array[@]}
do
mkdir -p ${i}
done